eureka:
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
server:
  port: 2222
